
spring:
    datasource:
        url: jdbc:mysql://bdg61450jonx94atjyzl-mysql.services.clever-cloud.com/bdg61450jonx94atjyzl
        username: uepxgpyld3hlwphr
        password: Tpsyevg16kXgsy60sTBb
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto : update
        show-sql: true
        properties: 
            hibernate:
                format_sql: true
        database: mysql
        databse-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    autoconfigure:
        exclude: 
server:
    port: 8080
